AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda local demo


Resources:
  LambdaDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ # format is projectPath/
      Handler: lambda.handler # format is filename.functionName
      Runtime: python3.7



  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apigateway/ # format is projectPath/
      Handler: lambda.handler # format is filename.functionName
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: GET